# Generated by Django 5.2.7 on 2025-12-17 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdata',
            old_name='Lab_name',
            new_name='lab_name',
        ),
    ]
